sudo: true

language: node_js
node_js:
  - "10"

install:
  - npm install --global npm
  - npm install
  - npm run build

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - npm test
