sudo: true

language: node_js
node_js:
  - "12"

install:
  - npm install --global npm
  - npm install --global lerna
  - lerna bootstrap --no-ci

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - npm test
