sudo: true

language: node_js
node_js:
  - "12"

install:
  - cp .baldr.json $HOME/.baldr.json
  - npm install --global npm
  - npm install --global lerna
  - lerna bootstrap --no-ci

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
services:
  - xvfb

script:
  - cd /home/travis/build/Josef-Friedrich/baldr/src/vue/apps/seating-plan; npm run test:unit
  - cd /home/travis/build/Josef-Friedrich/baldr/src/vue/apps/songbook; npm run test:unit

# https://docs.travis-ci.com/user/conditional-builds-stages-jobs
# https://docs.travis-ci.com/user/conditions-v1
if: tag IS blank
