dist: trusty
sudo: true

language: node_js
node_js:
  - "8"

env:
  - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true

install:
  - npm install --global npm
  - npm install
  - npm run dist

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - npm test

branches:
  only:
  - master
